'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Sample

    Partial Public Class dataEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=dataEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Categoria() As DbSet(Of Categoria)
        Public Overridable Property Genero() As DbSet(Of Genero)
        Public Overridable Property Log() As DbSet(Of Log)
        Public Overridable Property Pregunta() As DbSet(Of Pregunta)
        Public Overridable Property Respuesta() As DbSet(Of Respuesta)
        Public Overridable Property RespuestaXSesion() As DbSet(Of RespuestaXSesion)
        Public Overridable Property Sesion() As DbSet(Of Sesion)
        Public Overridable Property Tema() As DbSet(Of Tema)
        Public Overridable Property TipoLog() As DbSet(Of TipoLog)
        Public Overridable Property TipoUsuario() As DbSet(Of TipoUsuario)
        Public Overridable Property Usuario() As DbSet(Of Usuario)
        Public Overridable Property RespuestasPregunta() As DbSet(Of RespuestasPregunta)
    
    End Class

End Namespace
