'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Sample

    Partial Public Class Genero
        Public Property Id As Integer
        Public Property Descripcion As String
    
        Public Overridable Property Usuario As ICollection(Of Usuario) = New HashSet(Of Usuario)
    
    End Class

End Namespace
