'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Sample

    Partial Public Class Pregunta
        Public Property Id As Long
        Public Property Descripcion As String
        Public Property SelMultiple As Boolean
        Public Property TemaId As Nullable(Of Integer)
        Public Property CategoriaId As Nullable(Of Integer)
    
        Public Overridable Property Categoria As Categoria
        Public Overridable Property Tema As Tema
        Public Overridable Property RespuestaXSesion As ICollection(Of RespuestaXSesion) = New HashSet(Of RespuestaXSesion)
        Public Overridable Property Respuesta As ICollection(Of Respuesta) = New HashSet(Of Respuesta)
    
    End Class

End Namespace
