'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Sample

    Partial Public Class RespuestaXSesion
        Public Property Id As Long
        Public Property PreguntaId As Nullable(Of Long)
        Public Property RespuestaId As Nullable(Of Long)
        Public Property SesionId As Nullable(Of Long)
    
        Public Overridable Property Pregunta As Pregunta
        Public Overridable Property Respuesta As Respuesta
        Public Overridable Property Sesion As Sesion
    
    End Class

End Namespace
