'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Sample

    Partial Public Class RespuestasPregunta
        Public Property PreguntaId As Long
        Public Property Id As Long
        Public Property Descripcion As String
        Public Property Correcta As Nullable(Of Boolean)
    
    End Class

End Namespace
