'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Sample

    Partial Public Class Sesion
        Public Property Id As Long
        Public Property UsuarioId As Nullable(Of Integer)
        Public Property ContadorRespuestas As Nullable(Of Integer)
        Public Property MaxPreguntas As Nullable(Of Integer)
    
        Public Overridable Property RespuestaXSesion As ICollection(Of RespuestaXSesion) = New HashSet(Of RespuestaXSesion)
        Public Overridable Property Usuario As Usuario
    
    End Class

End Namespace
