'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property GeneroId As Nullable(Of Integer)
    Public Property TipoUsuarioId As Nullable(Of Integer)

    Public Overridable Property Genero As Genero
    Public Overridable Property Sesion As ICollection(Of Sesion) = New HashSet(Of Sesion)
    Public Overridable Property TipoUsuario As TipoUsuario

End Class
