'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property Id As Long
    Public Property Descripcion As String
    Public Property TipoLogId As Nullable(Of Integer)
    Public Property Fecha As Nullable(Of Date)

    Public Overridable Property TipoLog As TipoLog

End Class
